package com.novation.eligibility.domain.model;

public enum ContractExecutionEventType {
	MEMBER_INITIAL_REQUEST,
	SUPPLIER_APPROVAL,
	SUPPLIER_APPROVAL_REQUEST,
	SUPPLIER_TIER_CHANGE,
	MEMBER_ACCEPTANCE_NEW_TIER,
	DISTRIBUTOR_CONFIRMATION_REQUEST,
	SUPPLIER_DENY_REQUEST,
	SUPPLIER_BULK_REQUEST,
	HARD_COPY_INITIAL_REQUEST
}
